name: Cleanup Old Releases

on:
  workflow_dispatch: # Allows you to run this manually from the Actions tab

jobs:
  delete-old-releases:
    runs-on: ubuntu-latest
    permissions:
      contents: write 
      
    steps:
      - name: Delete all releases except the latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release list --repo ${{ github.repository }} --limit 100 --json tagName --jq '.[1:][].tagName' | \
          xargs -I {} gh release delete {} --repo ${{ github.repository }} --cleanup-tag -y
